In [16]:
from example import ex_matrix
from example import ex_TFIDF
import math

In [45]:
matrix = ex_matrix.matrix

In [18]:
ex_TFIDF.weight(matrix)

array([[ 0.  ,  0.44,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.74,  0.  ,  0.74,  0.  ,  0.  ,  0.  ,  0.  ,  0.74],
       [ 0.  ,  0.44,  0.  ,  0.  ,  0.44,  0.  ,  0.  ,  0.  ],
       [ 0.74,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.34,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.34,  0.44,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.44,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.34,  0.44,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.04,  1.04,  0.74],
       [ 0.  ,  0.  ,  0.74,  0.34,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.44,  0.  ,  0.34,  0.44,  0.  ,  0.  ,  0.  ]])

In [19]:
weights = ex_TFIDF.weight(matrix)

#### 1. norm을 구해본다.

In [20]:
def norm2(arr):
    sum = 0.0
    for i in range(0, len(arr)):
        sum += arr[i] * arr[i]
    return math.sqrt(sum)

In [42]:
print(weights[0],"=>",norm2(weights[0]))
print(weights[1],"=>",norm2(weights[1]))
print(weights[2],"=>",norm2(weights[2]))
print(weights[3],"=>",norm2(weights[3]))

[ 0.    0.44  0.    0.    0.    0.    0.    0.  ] => 0.43933269383026263
[ 0.74  0.    0.74  0.    0.    0.    0.    0.74] => 1.282345794232371
[ 0.    0.44  0.    0.    0.44  0.    0.    0.  ] => 0.621310254008664
[ 0.74  0.    0.    0.    0.    0.    0.    0.  ] => 0.7403626894942439


#### 2. Inner Product를 해본다.

In [22]:
def dot(arr1, arr2):
    sum = 0.0
    for i in range(0, len(arr1)):
        sum += arr1[i] * arr2[i]
    return sum

In [39]:
print(dot(weights[0], weights[1]))
print(dot(weights[0], weights[2]))
print(dot(weights[1], weights[3]))

0.0
0.193013215868
0.548136911995


#### 3.Cosine Similarity를 구해본다.

In [40]:
def cosine(arr1,arr2):
    return dot(arr1,arr2)/(norm2(arr1)*norm2(arr2))


In [41]:
print(cosine(weights[0], weights[1]))
print(cosine(weights[0], weights[2]))
print(cosine(weights[1], weights[3]))

0.0
0.707106781187
0.57735026919


### 라이브러리 Numpy를 이용해 쉽게사용해보자.
* numpy에서 axis 는 차원을 말한다.  행렬에선 행이냐 열이냐를 묻는다랑 동일하다
* 참고 doc => https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.norm.html

In [46]:
from numpy import linalg as LA

In [67]:
norms = LA.norm(weights,ord=2,axis=1) 
norms

array([ 0.44,  1.28,  0.62,  0.74,  0.34,  0.56,  0.44,  0.56,  1.65,  0.82,  0.71])