In [2]:
from example import ex_matrix
from example import ex_TFIDF
import math

In [3]:
matrix = ex_matrix.matrix

In [4]:
ex_TFIDF.weight(matrix)

array([[ 0.  ,  0.44,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.74,  0.  ,  0.74,  0.  ,  0.  ,  0.  ,  0.  ,  0.74],
       [ 0.  ,  0.44,  0.  ,  0.  ,  0.44,  0.  ,  0.  ,  0.  ],
       [ 0.74,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.34,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.34,  0.44,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.44,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.34,  0.44,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.04,  1.04,  0.74],
       [ 0.  ,  0.  ,  0.74,  0.34,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.44,  0.  ,  0.34,  0.44,  0.  ,  0.  ,  0.  ]])

In [5]:
weights = ex_TFIDF.weight(matrix)

#### 1. norm을 구해본다.

In [6]:
def norm2(arr):
    sum = 0.0
    for i in range(0, len(arr)):
        sum += arr[i] * arr[i]
    return math.sqrt(sum)

In [7]:
print(weights[0],"=>",norm2(weights[0]))
print(weights[1],"=>",norm2(weights[1]))
print(weights[2],"=>",norm2(weights[2]))
print(weights[3],"=>",norm2(weights[3]))

[ 0.    0.44  0.    0.    0.    0.    0.    0.  ] => 0.43933269383026263
[ 0.74  0.    0.74  0.    0.    0.    0.    0.74] => 1.282345794232371
[ 0.    0.44  0.    0.    0.44  0.    0.    0.  ] => 0.621310254008664
[ 0.74  0.    0.    0.    0.    0.    0.    0.  ] => 0.7403626894942439


#### 2. Inner Product를 해본다.

In [8]:
def dot(arr1, arr2):
    sum = 0.0
    for i in range(0, len(arr1)):
        sum += arr1[i] * arr2[i]
    return sum

In [9]:
print(dot(weights[0], weights[1]))
print(dot(weights[0], weights[0]))
print(dot(weights[0], weights[2]))
print(dot(weights[1], weights[3]))

0.0
0.193013215868
0.193013215868
0.548136911995


#### 3.Cosine Similarity를 구해본다.

In [10]:
def cosine(arr1,arr2):
    return dot(arr1,arr2)/(norm2(arr1)*norm2(arr2))


In [11]:
print(cosine(weights[0], weights[1]))
print(cosine(weights[0], weights[0]))
print(cosine(weights[0], weights[2]))
print(cosine(weights[1], weights[3]))

0.0
1.0
0.707106781187
0.57735026919


### 라이브러리 Numpy를 이용해 쉽게사용해보자.
* numpy에서 axis 는 차원을 말한다.  행렬에선 행이냐 열이냐를 묻는다랑 동일하다
* 참고 doc => https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.norm.html

In [12]:
from numpy import linalg as LA
import numpy as np

#### norm을 구해준다.

In [25]:
norms = LA.norm(weights,ord=2,axis=1) 
norms

array([ 0.44,  1.28,  0.62,  0.74,  0.34,  0.56,  0.44,  0.56,  1.65,  0.82,  0.71])

#### 내적한다. inner product
* 같은값은 역을 multiplelicative해주면 inner product이다. ( 용어가 확실한지모르겠음 두 백터 곱해주는 함수임)

In [26]:
dots = np.matmul(weights, weights.T)
dots

array([[ 0.19,  0.  ,  0.19,  0.  ,  0.  ,  0.  ,  0.19,  0.  ,  0.  ,  0.  ,  0.19],
       [ 0.  ,  1.64,  0.  ,  0.55,  0.  ,  0.  ,  0.  ,  0.  ,  0.55,  0.55,  0.  ],
       [ 0.19,  0.  ,  0.39,  0.  ,  0.  ,  0.19,  0.19,  0.19,  0.  ,  0.  ,  0.39],
       [ 0.  ,  0.55,  0.  ,  0.55,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.12,  0.12,  0.  ,  0.12,  0.  ,  0.12,  0.12],
       [ 0.  ,  0.  ,  0.19,  0.  ,  0.12,  0.31,  0.  ,  0.31,  0.  ,  0.12,  0.31],
       [ 0.19,  0.  ,  0.19,  0.  ,  0.  ,  0.  ,  0.19,  0.  ,  0.  ,  0.  ,  0.19],
       [ 0.  ,  0.  ,  0.19,  0.  ,  0.12,  0.31,  0.  ,  0.31,  0.  ,  0.12,  0.31],
       [ 0.  ,  0.55,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  2.72,  0.  ,  0.  ],
       [ 0.  ,  0.55,  0.  ,  0.  ,  0.12,  0.12,  0.  ,  0.12,  0.  ,  0.67,  0.12],
       [ 0.19,  0.  ,  0.39,  0.  ,  0.12,  0.31,  0.19,  0.31,  0.  ,  0.12,  0.5 ]])

#### cosine similarity를 구해준다.
* 바로 아래있는건 잘못된것임. 한칸더 아래있는게 맞는거임 왜 다른 값이 나오는지 모르겠음...
* 근데.T를 왜붙이는지 모르겠음 => 아마도 식맞춰주기위에 큰 부분에 T를 붙이는거같은데 정확한이유 모르겠음.

In [23]:
np.divide(dots,norms)*norms

ValueError: operands could not be broadcast together with shapes (8,8) (11,) 

In [27]:
sims = np.divide(np.divide(dots, norms).T, norms)
sims

array([[ 1.  ,  0.  ,  0.71,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.62],
       [ 0.  ,  1.  ,  0.  ,  0.58,  0.  ,  0.  ,  0.  ,  0.  ,  0.26,  0.52,  0.  ],
       [ 0.71,  0.  ,  1.  ,  0.  ,  0.  ,  0.56,  0.71,  0.56,  0.  ,  0.  ,  0.88],
       [ 0.  ,  0.58,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.61,  0.  ,  0.61,  0.  ,  0.42,  0.48],
       [ 0.  ,  0.  ,  0.56,  0.  ,  0.61,  1.  ,  0.  ,  1.  ,  0.  ,  0.26,  0.79],
       [ 1.  ,  0.  ,  0.71,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.62],
       [ 0.  ,  0.  ,  0.56,  0.  ,  0.61,  1.  ,  0.  ,  1.  ,  0.  ,  0.26,  0.79],
       [ 0.  ,  0.26,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.52,  0.  ,  0.  ,  0.42,  0.26,  0.  ,  0.26,  0.  ,  1.  ,  0.2 ],
       [ 0.62,  0.  ,  0.88,  0.  ,  0.48,  0.79,  0.62,  0.79,  0.  ,  0.2 ,  1.  ]])

### 예제파일로 만들어준다.

In [76]:
%%writefile example/ex_CosineSimilarity.py

from numpy import linalg as LA
import numpy as np
norms = LA.norm(weights,ord=2,axis=1) 
dots = np.matmul(weights, weights.T)
sims = np.divide(np.divide(dots, norms).T, norms)
return sims

Writing example/ex_CosineSimilarity.py
